### ISSUE TITLE
could you please tell me where to obtain this file: weights/model-vit-ang-loss.h5?

### ISSUE THREAD

**Issue by pongjy123** [pidahbus/deep-image-orientation-angle-detection#13]
Hello, could you please tell me where to obtain this file: weights/model-vit-ang-loss.h5? I encountered the following error during training: OSError: Unable to open file (unable to open file: name = 'weights/model-vit-ang-loss.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0).

**Comment by pidahbus** [comment]
Please go through the readme. The model is available here, https://drive.google.com/file/d/1sdmPmaDhivdHPfn9M9vAkTbiprbPq94e/view
