### ISSUE TITLE
Question about the validation and test sets

### ISSUE THREAD

**Issue by danielcmm** [pidahbus/deep-image-orientation-angle-detection#5]
Hi! Thanks for the repo!

Im not sure i understood how the validation and test images should be placed on their folders.
If the images need to be placed with the correct orientation on these folders, what should i put on the angle column of the validation-test.csv file?

Thanks!

**Comment by pidahbus** [comment]
yes, validation and test images need to be placed with the correct orientation. These images would be rotated with the corresponding angles put in the angle column. After that the model will predict the orientation angle and based on the model's prediction angles and the angles (true angle) mentioned in the angle column, the validation score will be generated. To start with you can put random angles in the angle column as true values and check how good your model is predicting those angles.

I hope this answers your query. I will take your question as a feedback and update my README file. Thanks.

**Comment by danielcmm** [comment]
Thank you very much!!
