### ISSUE TITLE
vit model does not detect orientation of provided samples

### ISSUE THREAD

**Issue by ielenik** [pidahbus/deep-image-orientation-angle-detection#6]
Should it ever work?
image.jpg ->
2023-06-16 13:48:36.656 | INFO     | __main__:predict:22 - Predicted angle is: -0.945604681968689 degree

**Comment by pidahbus** [comment]
May I know which `image.jpg` you are using? If you take it from the `preds` folder then the prediction is correct.

**Comment by ielenik** [comment]
image is from 'inputs' folder
that is the command line
python infer.py --image-path=./inputs/image.jpg
Is prediction as expected? Or there is something wrong with my local setup?

**Comment by pidahbus** [comment]
the prediction angle should be 116 degree. Could you double check if the `image.jpg` is the same as the `image.jpg` in the `inputs` folder of my repository?

**Comment by ielenik** [comment]
Sorry, sir, that is my fault
The image was correct, but the model was with default weights - trained weights have not loaded somehow
Thank you for your repository, I will try use model prediction to align my panoramas verticaly
BTW panoramas can be the good source for training such models, publicity available panoramas usualy aligned vertically and it is possible from one sample get multiple projections with different angles and without borders and other artifacts.
